ReadingSpace CRUD  기능 구현
f-lab-edu/three-sentences pull request #14
Opened 2023-02-04 06:37 UTC by shinsanghooon

## ReadingSpace 생성
 - #8 
- - [x] 사용자는 계정 생성과 동시에 본인의 ReadingSpace가 생성된다. 
- - [x] 사용자는 ReadingSpace를 생성할 수 있으며, 여러 개의 ReadingSpace에 속할 수 있다.
- - [x] ReadingSpace를 생성한 사용자는 admin의 역할을 갖게 된다.
- - [x] 그룹 정보(이름, 설명, 공개여부, 프로필 이미지)를 입력받아 그룹을 생성할 수 있다. 
- - [x] 공개여부는 PUBLIC, PRIVATE 두 가지만 존재한다.
- - [x] 그룹은 이름을 기준으로 전체 애플리케이션에서 유니크하게 관리된다. 

## ReadingSpace 조회
- #13 
- - [x] 모든 사용자는 public으로 설정된 ReadingSpace를 조회할 수 있다.
- - [x] 사용자는 본인이 속한 private ReadingSpace도 조회할 수 있다. 

## ReadingSpace 수정
- #12 
- - [x] 설명, 공개여부, 프로필 이미지를 수정할 수 있다. 

## ReadingSpace 삭제
- #11 
- - [x] 그룹에 참여 중인 사용자(어드민 제외)가 있는 경우 삭제가 불가능하다. (삭제를 하려면 소속된 회원을 강제 탈퇴 시킨 후에 삭제가 가능하다.)
- - [x] soft delete 형태로 구현하기

#### <i>단위 테스트는 아직 못했습니다. 추가로 진행하도록 하겠습니다. </i>

2023-02-04 13:14 UTC, kyucumber requested changes

2023-02-04 13:14 UTC, kyucumber commented on src/main/java/com/sh/threesentences/common/dto/ErrorResponseDto.java
> +    private int httpStatusCode;
둘중 하나만 써도 되지 않을까요~?

2023-02-04 13:14 UTC, kyucumber commented on src/main/java/com/sh/threesentences/common/exception/CommonExceptionHandler.java
> +    @ResponseStatus(code= BAD_REQUEST)
요렇게 lint가 깨지는게 지속적으로 보이는데 로컬에 pre-commit hook을 설정해두시는게 어떨까 싶네요~

2023-02-04 13:14 UTC, kyucumber commented on src/main/java/com/sh/threesentences/readingspace/controller/ReadingSpaceController.java
> +@RequestMapping("/api/v1/readingspaces")
기존에 클래스 설계하실때는 ReadingSpace로 space 앞에 카멜케이스로 구분을 주셨던 것 같아요 아무래도 url 규칙 상 CamelCase로 사용하기 어색해서 소문자로 쭉 이어붙여 표기하신 것 같은데요.

hyphen을 붙여서 표현하셔도 될 것 같아요. 참고하시라고 코멘트 남겼습니다.

https://stackoverflow.com/questions/10302179/hyphen-underscore-or-camelcase-as-word-delimiter-in-uris

2023-02-04 13:14 UTC, kyucumber commented on src/main/java/com/sh/threesentences/readingspace/controller/ReadingSpaceController.java
> +    @GetMapping("")
""는 생략하셔도 될 것 같습니다.

2023-02-04 13:14 UTC, kyucumber commented on src/main/java/com/sh/threesentences/readingspace/controller/ReadingSpaceController.java
> +    @ResponseStatus(HttpStatus.CREATED)
Created 응답에는 생성된 리소스에 대해 Redirect 할 수 있도록 Location 헤더에 해당 자원의 경로를 나타내기도 합니다. 꼭 붙여야 하는 것은 아니지만 참고 부탁드려요.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Location

2023-02-04 13:14 UTC, kyucumber commented on src/main/java/com/sh/threesentences/common/exception/ErrorCode.java
> +    READING_SPACE_NOT_FOUND(BAD_REQUEST, "존재하지 않는 ReadingSpace 입니다.");
이렇게 관리하시면 프로젝트의 막바지에 결국 ErrorCode enum이 수십, 많게는 수백개가 넘게 되기도 합니다. 이렇게 한 곳에서 관리하는 것 보다 각각의 도메인(ReadingSpace, User 등)에서 에러에 대한 메시지를 별도로 관리하는게 더 나은 선택이 될 수도 있습니다.

한번 고민해보시면 좋겠네요~

2023-02-04 13:14 UTC, kyucumber commented on src/main/java/com/sh/threesentences/readingspace/controller/ReadingSpaceController.java
> +     */
저번에도 한번 코멘트 남겼다가 계속 남기시길래 별도로 말씀은 안드렸는데요. 요런 정보는 주석으로 남기지 않아도 괜찮지 않을까요?
Get에서 조회인게 드러나고, 리턴 타입도 `List<ReadingSpace>`로 표시가 되는데 굳이 별도로 남길 필요가 있는지 잘 모르겠어서요.

2023-02-04 13:14 UTC, kyucumber commented on src/main/java/com/sh/threesentences/readingspace/entity/ReadingSpace.java
> +    @JsonManagedReference
현재 응답은 엔티티가 아니라 Dto를 사용하시는 것 같은데 해당 어노테이션을 따로 붙이신 이유가 있나요?

2023-02-04 13:14 UTC, kyucumber commented on src/main/java/com/sh/threesentences/readingspace/entity/ReadingSpace.java
> +    private List<UserReadingSpaceMapping> userReadingSpaceMappingList;
요건 개인 취향일 수 있는데 `List` 인터페이스에서 List가 드러나기 때문에 변수명에 List가 중복으로 포함될 필요는 없지 않을까 생각되네요. Mappings와 같이 복수형으로 표시하셔도 좋을 것 같아요~

2023-02-04 13:14 UTC, kyucumber commented on src/main/java/com/sh/threesentences/readingspace/service/ReadingSpaceService.java
> +    }
DDD(Domain Driven Development)에서는 도메인 서비스라는 개념이 있습니다. 이는 값 객체나 엔티티로 구현하기 어색한 행동들을 정의하는 서비스입니다.

이런 복잡한 로직은 별도로 도메인 서비스 등을 분리해 처리해보실수도 있을 것 같아요.

```kotlin
readingSpaceDomainService.checkDeleteCondition(readingSpace);
```

> 도메인에 들어갈 내용이 도메인 서비스로 다 빠지는 경우 도메인 객체가 빈약해질 수 있으므로 가급적 도메인 서비스의 생성은 피하는게 좋습니다.

사실 아직은 서비스의 복잡도가 높지 않아 고려하시지 않아도 되는데 이런 로직이 늘어나면 결국 이 서비스의 복잡도가 계속 올라가고 관리하기 어려워집니다.

이후에 서비스의 복잡도가 올라가면 도메인 서비스로 추출하는 것과 Update, Create 등을 분리하는것도 고려해보세요.

2023-02-04 13:14 UTC, kyucumber commented on src/main/java/com/sh/threesentences/readingspace/service/ReadingSpaceService.java
> +        } else if (readingSpaceMembers.size() == 1) {
`size() >= 2`, `size() = 1`각각이 어떤걸 의미하는지 알 수 없으니 주석을 다 남겨주셨네요.

이런 경우는 `readingSpaceMembers.is~~~()`와 같이 메소드를 정의해주시면 서비스의 책임을 줄일 수 있습니다.

`List<UserReadingSpaceMapping>`을 일급 컬렉션으로 래핑해서 위와 같이 메소드를 만들어보셔도 좋을 것 같네요.

https://jojoldu.tistory.com/412

2023-02-04 13:14 UTC, kyucumber commented on src/main/java/com/sh/threesentences/readingspace/entity/UserReadingSpaceMapping.java
> +    private UserRole userRole;
ReadingSpace에 속한 유저를 관리하기 위해 만드신 엔티티인가요?

User까지는 이해가 가는데 ReadingSpace가 또 들어있는 이유는 무엇인지, UserRole이 여기에 들어있는 이유는 무엇인지 여러가지가 잘 이해가 되지 않네요. 요건 좀 자세히 코멘트를 남겨주시거나 멘토링때 같이 이야기해보면 좋을 것 같습니다.

2023-02-04 13:44 UTC, shinsanghooon commented on src/main/java/com/sh/threesentences/readingspace/controller/ReadingSpaceController.java
> +@RequestMapping("/api/v1/readingspaces")
확인해보겠습니다 !

2023-02-04 13:45 UTC, shinsanghooon commented on src/main/java/com/sh/threesentences/readingspace/controller/ReadingSpaceController.java
> +    @ResponseStatus(HttpStatus.CREATED)
확인해보겠습니다 !

2023-02-04 13:52 UTC, shinsanghooon commented on src/main/java/com/sh/threesentences/readingspace/entity/UserReadingSpaceMapping.java
> +    private UserRole userRole;
User와 ReadingSpace는 다대다 관계이고 UserReadingSpaceMapping은 ReadingSpace에 속한 User가 각 Space에서 어떤 역할을 가지고 있는지를 표현해주기 위한 엔티티입니다. 

예를 들어, 
A라는 유저는 Java라는 Space에 속할 수 있고 Java 스페이스에서는 일반 유저일 수 있습니다. 
그리고 A라는 유저가 Spring 이라는 Space를 직접 만들게 되면 이때는 A는 Spring Space의 어드민이 되게 됩니다.

위의 예시와 같은 이유로 UserRole을 필드로 사용하게 만들었습니다.

2023-02-04 13:57 UTC, shinsanghooon commented on src/main/java/com/sh/threesentences/readingspace/entity/ReadingSpace.java
> +    @JsonManagedReference
계속 Infinite Recursion 문제가 발생해서 적용을 했습니다. 요 부분은 저도 조금 더 자세히 알아보겠습니다.

2023-02-05 14:47 UTC, shinsanghooon commented on src/main/java/com/sh/threesentences/common/exception/ErrorCode.java
> +    READING_SPACE_NOT_FOUND(BAD_REQUEST, "존재하지 않는 ReadingSpace 입니다.");
ErrorCode가 대단히 복잡하지는 않다고 생각하기도 했고 저정도로 많아질 수 있을거라고 상상을 못했네요.  도메인 별로 따로 관리하는게 관리도 쉽고 코드도 더욱 깔끔해질 것 같습니다.

2023-02-05 15:10 UTC, shinsanghooon commented on src/main/java/com/sh/threesentences/readingspace/service/ReadingSpaceService.java
> +        } else if (readingSpaceMembers.size() == 1) {
해당 조건들은 메소드로 분리하면서 이름을 짓다가 갑자기 혼란이 생겼습니다! 

만약 `readingSpace.size() >= 2 ` 를 `isGreaterThanOne()` 해당 메소드로 추출했다고 하면  멤버 수가 2명 이상이어야 한다는 조건 자체는 동일하지만, 뭔가... 주석에 적힌 의미를 잘 전달하지는 못하는 것 같습니다. 

그렇다면 
- 2명 이상인 경우 삭제를 못한다는 주석을 남겨 놓아야 하는 걸까요?
- 메소드 이름을 사용자가 2명 이상이면 삭제를 못한다!는 의미를 가진 메소드 명을 지어야 하는 걸까요? 
- 아니면 2명 이상인 경우, 어차피 관련 메시지를 포함한 예외를 던지기 때문에 충분히 의미 전달이 된다고 봐도 되는 걸까요? 

저는 3번째라고 생각이 들긴 하는데, 멘토님의 의견은 어떠신지 궁금합니다!

2023-02-08 11:48 UTC, kyucumber requested changes

2023-02-08 11:48 UTC, kyucumber commented on src/main/java/com/sh/threesentences/readingspace/entity/UserReadingSpaceMapping.java
> +    @JoinColumn(name = "readingspace_id")
현재 카멜케이스로 정의하신 걸 봤을 때 reading_space_id가 좀 더 컨벤션에 맞는 이름이 아닐까 생각되네요.

2023-02-08 11:48 UTC, kyucumber commented on src/main/java/com/sh/threesentences/readingspace/entity/UserReadingSpaceMappingKey.java
> +public class UserReadingSpaceMappingKey implements Serializable {
`@Id` 어노테이션을 고려했을 때 복합키라 하더라도 ~Key 보다는 Id로 네이밍해도 괜찮지 않을까 싶네요~

2023-02-08 11:48 UTC, kyucumber commented on src/main/java/com/sh/threesentences/readingspace/entity/UserReadingSpaceMapping.java
> +    public static UserReadingSpaceMapping createUserReadingSpaceMapping(User user, ReadingSpace readingSpace,
이런 경우 static method 보단 생성자가 더 코드가 짧을 것 같은데 생성자를 사용하는건 어떨까요?

```java
public UserReadingSpaceMapping(User user, ReadingSpace readingSpace, UserRole userRole) {
        this.id = new UserReadingSpaceMappingKey(user.getId(), readingSpace.getId());
        this.user = user;
        this.readingSpace = readingSpace;
        this.userRole = userRole;
    }
```

- 생성자 사용
```java
UserReadingSpaceMapping userReadingSpaceMapping = new UserReadingSpaceMapping(user, savedReadingSpace, UserRole.ADMIN);
```

- 정적 팩토리 메소드 사용
```java
UserReadingSpaceMapping userReadingSpaceMapping = UserReadingSpaceMapping.createUserReadingSpaceMapping(user, savedReadingSpace, UserRole.ADMIN);
```

2023-02-08 11:48 UTC, kyucumber commented on src/main/java/com/sh/threesentences/readingspace/entity/UserReadingSpaceMapping.java
> +    private UserRole userRole;
제가 엔티티를 잘못 본 부분이 있어서 이해가 되지 않는다고 남겼군요.. 잘 만들어주셨습니다. 👍 

대신 ReadingSpace를 삭제하거나 수정할 때 권한 체크를 하는 부분을 조금 주의해서 작성하셔야 할 것 같긴 하네요~
ReadingSpace에 참여한 유저가 수천명이거나, 유저가 권한을 가진 ReadingSpace가 수천개인 경우(이런 경우는 많진 않을 것 같긴 해요) 엔티티 그래프의 관계를 이용하게 되면 컬렉션을 조회하면서 불필요한 데이터를 많이 조회할 것 같거든요.

2023-02-08 11:48 UTC, kyucumber commented on src/main/java/com/sh/threesentences/readingspace/entity/UserReadingSpaceMapping.java
> +public class UserReadingSpaceMapping {
사실 이름이 아주 명확하게 지어지긴 했는데 권한(ADMIN, REDINGMATE)에 대한 부분이 전혀 드러나지 않아 조금 아쉽고 헷갈리네요. 

처음에 코멘트 남긴 부분도 이름 때문에 오해하고 잘못 확인한 부분이 있었거든요. 권한 관리에 대한 부분이 드러나게 ReadingSpaceRole과 같은 이름은 어떨까 싶기도 하네요.

2023-02-08 11:48 UTC, kyucumber commented on src/main/java/com/sh/threesentences/readingspace/service/ReadingSpaceService.java
> +        } else if (readingSpaceMembers.size() == 1) {
말씀하신것 처럼 isGreaterThanOne으론 의도하신 부분이 아주 잘 드러나진 않죠.

3번째로 하셔도 충분히 의미 전달은 잘 될 것 같아요. 다만 한번 더 코드를 살펴보아야하는 번거로움이 있겠죠. 이런 경우 isGreaterThanOne을 추출하시고 또 아래와 같은 메소드를 추출해 사용하면 해결되지 않을까 싶네요.

```java
private checkMemberExists() {}
private checkAdmin() {}
private checkOneMember() {} 
private checkNoMember() {}
```

2023-02-08 11:48 UTC, kyucumber commented on src/main/java/com/sh/threesentences/readingspace/service/ReadingSpaceService.java
> +        } else if (readingSpaceMembers.size() == 1) {
이거 일급 컬렉션 내부에서 검증하는게 객체지향적으로는 자연스럽고, 데이터가 엄청 많지 않으면 큰 성능 문제가 있을 것 같진 않은데요.

컬렉션 타입이라 전체를 다 조회한다음에 size()로 데이터를 가져오게 될 것 같아요. 일급 컬렉션이 아니라 별도의 도메인 서비스를 분리하고 내부에서 count 쿼리를 날려 검증하는 형태가 적절하지 않을까 생각되네요.

2023-02-10 12:59 UTC, kyucumber approved these changes

2023-02-10 13:47 UTC, merged