사용자 인증 기능 구현
f-lab-edu/three-sentences pull request #17
Opened 2023-02-12 17:15 UTC by shinsanghooon

### 사용자 인증 기능 구현 
- [x] 로그인, 로그아웃 기능 구현
- [x] 스프링 시큐리티 활용
- [x] JSESSIONID 쿠키 값을 이용해서 로그인 유지 
- [ ] 단위 테스트 작성 
- Closes #15, closes #16

2023-02-14 14:03 UTC, f-lab-kyucumber requested changes

2023-02-14 14:03 UTC, f-lab-kyucumber commented on src/main/java/com/sh/threesentences/ThreeSentencesApplication.java
>      }
요런건 AuthConfig에 넣는건 어떨까요~?

2023-02-14 14:03 UTC, f-lab-kyucumber commented on src/main/java/com/sh/threesentences/auth/config/AuthConfig.java
> +        http.csrf().disable();
혹시 csrf를 disable하신 이유는 무엇인가요~?

2023-02-14 14:03 UTC, f-lab-kyucumber commented on src/main/java/com/sh/threesentences/auth/dto/LoginDto.java
> +    String password;
```suggestion
    private final String email;

    private final String password;
```

중요한건 아니지만 잊지 않고 붙여주시면 좋을 것 같아요~

2023-02-14 14:03 UTC, f-lab-kyucumber commented on src/main/java/com/sh/threesentences/auth/dto/LoginDto.java
> +    String password;
여기도 빈 값 등이 올 수 없게 NotBlank 등의 어노테이션을 붙이고 `@Valid`로 검증하면 어떨까요?

2023-02-14 14:03 UTC, f-lab-kyucumber commented on src/main/java/com/sh/threesentences/users/entity/User.java
> +    private String authorityType = AuthorityType.BASIC.getName();
AuthorityType.ADMIN은 이 플랫폼 자체의 관리자라고 보면 될까요?

2023-02-14 14:03 UTC, f-lab-kyucumber commented on src/main/java/com/sh/threesentences/auth/service/AuthService.java
> +@Transactional
```suggestion
@Transactional(readOnly = true)
```

이후에 쓰기 작업이 추가되면 문제가 될 순 있지만 AuthService의 특성상 그러지 않을 것 같아서 추가하면 좋을 것 같네요.

2023-02-14 14:03 UTC, f-lab-kyucumber commented on src/main/java/com/sh/threesentences/auth/service/CustomAuthenticationProvider.java
> +    }
checkPassword 메소드가 체크와 Authentication 반환 두가지 역할을 하고 있어서 조금 어색한 것 같아요.

패스워드 체크는 SecurityUser로 책임을 옮기고 Authentication(UsernamePasswordAuthenticationToken)로 변환하는 메소드를 별도로 만들거나 하는건 어떨까요?

2023-02-14 14:03 UTC, f-lab-kyucumber commented on src/main/java/com/sh/threesentences/auth/service/AuthService.java
> +    }
Filter를 활용하고 하면 복잡해지는데 심플하게 AuthenticationManager만 활용해서 구현하셨군요. 책에 예제가 요렇게 되어있었나요~?

2023-02-14 14:03 UTC, f-lab-kyucumber commented on src/main/java/com/sh/threesentences/common/config/AuditorAwareImpl.java
> +public class AuditorAwareImpl implements AuditorAware<String> {
~~Impl보단 요거 Authentication에서 이메일을 추출하고 있으니 조금 더 구체적으로 이름을 지어도 좋을 것 같네요. 
개인적인 취향이라 무시하셔도 좋지만 ~~Impl이라는 이름을 그렇게 좋아하지 않아서요 🙂

2023-02-14 14:03 UTC, f-lab-kyucumber commented on src/main/java/com/sh/threesentences/readingspace/controller/ReadingSpaceController.java
> +        return readingSpaceService.create(readingSpaceRequestDto, auth.getName());
이거 Authentication 인터페이스 그대로 쓰시려니 getName이 email인지 뭔지 알기도 어렵고 좀 헷갈리지 않으시던가요? 

필요하면 Authentication 요 인터페이스 직접 구현하셔서 커스텀한 클래스를 만들어서 쓰셔도 될 것 같습니다.

2023-02-14 14:03 UTC, f-lab-kyucumber commented on src/main/java/com/sh/threesentences/readingspace/service/ReadingSpaceService.java
> +        ReadingSpace savedReadingSpace = createReadingSpace(
요거 save가 빠진걸까요? 내부에서 만드신 ReadingSpace를 저장하거나 반환값을 받아서 저장하는 로직이 보이지 않는것 같아요.

2023-02-14 14:03 UTC, f-lab-kyucumber commented on src/main/java/com/sh/threesentences/readingspace/service/ReadingSpaceService.java
> +                -> new IllegalStateException(READING_SPACE_NOT_FOUND.getMessage()));
여기 로직이 조금 복잡하네요. ReadingSpace의 id를 넘겨서 해당하는 ReadingSpaceMemberRole을 바로 받아올 수 있도록 User 클래스의 메소드로 추출해보아도 좋을 것 같아요.

2023-02-14 14:03 UTC, f-lab-kyucumber commented on src/main/java/com/sh/threesentences/readingspace/service/ReadingSpaceService.java
> +        if (!spaceMemberRole.getUserRole().equals(UserRole.ADMIN)) {
디미터 법칙을 위반하고 있습니다. isAdmin()과 같은 메소드를 만드는건 어떨까요?

2023-02-16 15:14 UTC, shinsanghooon commented on src/main/java/com/sh/threesentences/ThreeSentencesApplication.java
>      }
넵 말씀대로 authconfig에 넣는게 더 좋을 것 같습니다!

2023-02-16 15:15 UTC, shinsanghooon commented on src/main/java/com/sh/threesentences/auth/config/AuthConfig.java
> +        http.csrf().disable();
테스트를 위해서 disable 하였습니다. 
* 추후 csrf 토큰을 추가하거나, 로그인 방식은 jwt로 변경을 진행해보겠습니다.

2023-02-16 15:17 UTC, shinsanghooon commented on src/main/java/com/sh/threesentences/users/entity/User.java
> +    private String authorityType = AuthorityType.BASIC.getName();
넵 플랫폼 자체의 관리자가 맞습니다! AuthorityType.BASIC은 관리자 외의 일반 사용자 계정을 의미합니다.

2023-02-16 15:23 UTC, shinsanghooon commented on src/main/java/com/sh/threesentences/readingspace/service/ReadingSpaceService.java
> +        if (!spaceMemberRole.getUserRole().equals(UserRole.ADMIN)) {
네. 디미터 법칙에 대해서 알아보고 수정할 수 있도록 해보겠습니다. 

**디미터 법칙 간단 정의**
- 객체에게 자료를 숨기는 대신 함수를 공개. 다른 객체가 어떠한 자료를 갖고 있는지 몰라야 한다는 것을 의미
- 디미터 법칙을 준수함으로써 캡슐화 정도를 높여 객체의 자율성과 응집도를 높일 수 있음

2023-02-16 15:36 UTC, shinsanghooon commented on src/main/java/com/sh/threesentences/readingspace/service/ReadingSpaceService.java
> +        ReadingSpace savedReadingSpace = createReadingSpace(
바로 밑에 createReadingSpace라는 메소드에서 save를 호출합니다.

2023-02-16 15:38 UTC, shinsanghooon commented on src/main/java/com/sh/threesentences/common/config/AuditorAwareImpl.java
> +public class AuditorAwareImpl implements AuditorAware<String> {
음 더 좋은 이름을 한 번 고민해보겠습니다!

2023-02-16 15:44 UTC, shinsanghooon commented on src/main/java/com/sh/threesentences/readingspace/controller/ReadingSpaceController.java
> +        return readingSpaceService.create(readingSpaceRequestDto, auth.getName());
사실 .. 맞습니다... 이메일을 받아오는데 getName 메소드를 호출하는 것 자체가 찝찝햇는데 인터페이스를 커스텀하게 구현할 생각을 못했네요. 반영해보겠습니다.

2023-02-16 16:02 UTC, shinsanghooon commented on src/main/java/com/sh/threesentences/auth/service/AuthService.java
> +    }
넵. AuthenticationManager가 AuthenticationProvider에게 인증 처리를 위임하는 형태로 설명되어 있었습니다.

2023-02-18 02:22 UTC, shinsanghooon commented on src/main/java/com/sh/threesentences/ThreeSentencesApplication.java
>      }
PasswordEncoder를 AuthConfig로 옮겼을 때 AuthConfig <-> AuthenticationProvider 사이에 순환참조 문제가 발생합니다. 이런 저런 시도를 해봤는데 Spring Security에서 제공해주는 구조를 유지해주면서 적용하는게 어려워서 원래대로 Application 쪽에 PasswordEncoder를 넣어놨습니다. 
관련해서 멘토님의 의견을 여쭙고자 합니다. 해결할 수 있는 힌트를 주시면 또 고민해보도록 하겠습니다.

2023-02-18 02:29 UTC, shinsanghooon commented on src/main/java/com/sh/threesentences/auth/config/EmailAuthentication.java
> +        return getName();
Authentication 인터페이스를 구현한 EmailAuthentication을 만들었습니다. 기존의 getName 메소드를 결과를 그대로 반환해주는 getEmail 메소드만 추가했는데, 이런식으로 구현하는 것이 맞을까요?

2023-02-18 02:42 UTC, shinsanghooon commented on src/main/java/com/sh/threesentences/auth/service/CustomAuthenticationProvider.java
> +        if (!userDetails.checkPassword(username, password, passwordEncoder)) {
UserDetail 인터페이스를 구현한 SecurityUser에 checkPassword 메소드를 추가하였습니다. 
여기서 궁금한 점은 jpaUserDetailService를 구체클래스가 아닌 UserDetailsService 인터페이스로 받아오기 때문에, loadUserByUsername 메소드에서 반환되는 타입이 기본적으로 UserDetails입니다. 그래서 checkPassword 메소드를 사용해주기 위해서 SecurityUser로 형변환을 해줘야 하는 과정이 발생합니다. 
이러한 과정이 일반적인건지 아니면 조금 더 깔끔하게 적용할 수 있는 방법이 있는지 궁금합니다. 

jpaUserDetailService 타입을 JpaUserDetailService로 하면 간단하게 해결은 되지만 구체클래스에 의존하지 않도록 만들어 보고 싶었습니다..!

2023-02-18 02:45 UTC, shinsanghooon commented on src/test/java/com/sh/threesentences/users/service/UserServiceTest.java
> +        readingSpaceRepository.deleteAll();
데이터를 삭제할 때는 soft delete를 사용하기 때문에 JPA `Cascade.DELETE` 옵션은 불필요하다고 생각했습니다. 그런데 테스트를 할 때 rollback이 되면서 foreign key 제약 조건 때문에 DB delete 과정에서 에러가 발생해서 테스트가 진행되지 못했습니다. 이런 케이스를 위해 `Cascade.DELETE` 옵션을 엔티티에 추가해주는게 맞는지 궁금합니다  멘토님이 테스트를 위해서 서비스 코드를 수정하는 것은 하지 않는 것이 좋다고 하신 것이 기억나서 지금은 `@AfterEach`에서 관련 repository를 전체 삭제하도록 코드를 작성하였습니다.

2023-02-18 02:48 UTC, shinsanghooon commented on src/main/java/com/sh/threesentences/auth/config/AuthConfig.java
> +
`PasswordEncoder`를 `AuthConfig`로 옮겼을 때 `AuthConfig` <-> `AuthenticationProvider` 사이에 순환참조 문제가 발생합니다. 이런 저런 시도를 해봤는데 Spring Security에서 제공해주는 구조를 유지해주면서 적용하는게 어려워서 원래대로 `Application` 쪽에 `PasswordEncoder`를 넣어놨습니다.
관련해서 멘토님의 의견을 여쭙고자 합니다. 해결할 수 있는 힌트를 주시면 또 고민해보도록 하겠습니다.

2023-02-18 07:37 UTC, f-lab-kyucumber commented on src/main/java/com/sh/threesentences/auth/config/EmailAuthentication.java
> +        return getName();
음 제가 의도한 부분이랑은 좀 다릅니다.

CustomAuthenticationProvider에서 지금 UsernamePasswordAuthenticationToken을 반환하고 있는데 UsernamePasswordAuthenticationToken가 아니라 만드신 Authentication 구현체를 넣길 의도했거든요.

2023-02-18 07:40 UTC, f-lab-kyucumber commented on src/main/java/com/sh/threesentences/auth/service/CustomAuthenticationProvider.java
> +        if (!userDetails.checkPassword(username, password, passwordEncoder)) {
구체 타입이 아니라 인터페이스를 의존하게 하실거면 캐스팅 말곤 방법이 없을 듯 합니다. 추상화가 많이 된 라이브러리나 프레임워크를 쓰는 경우면 어쩔수 없이 캐스팅이 들어갈수밖에 없는 부분이 꽤나 있어서 일반적인 상황으로 보여요.

요게 거슬리면 구체 타입을 주입하도록 변경하시는게 좋을듯 합니다.

2023-02-18 07:49 UTC, f-lab-kyucumber commented on src/test/java/com/sh/threesentences/users/service/UserServiceTest.java
> +        readingSpaceRepository.deleteAll();
테스트를 위해서 CasCade 옵션을 넣는것은 개발자들에게 혼란을 줄 수 있어 보입니다. 따라서 넣지 않고 지금과 같은 형태로 deleteAll을 호출하시는게 나을 것 같아요.

그리고 위의 문제와 별개로 아래와 같은 고민이 있습니다.

1. 서비스 테스트가 SpringBootTest일 필요가 있을까?

서비스 테스트는 서비스 로직만을 테스트하고 실제 데이터베이스에서 데이터를 가져오는 부분은 필요에 따라 Repository에 대한 테스트를 SpringBootTest로 작성하셨으면 서비스 테스트에서 이런 문제가 발생하지 않았을 것 같아요.

2. soft delete가 부모 엔티티에만 적용되어 있어도 될까?

이번에 발생하신 케이스와 별개로 ReadingSpace가 soft delete인데 연관관계를 맺는 자식 엔티티를 삭제하는 부분이 안보이네요. 아예 삭제해버리거나 ReadingSpace 권한에 대한 기록이 필요하면 별도로 남기거나 연관관계를 맺는 자식 엔티티도 soft delete를 사용하도록 변경하시면 좋을 것 같습니다.

2023-02-18 07:49 UTC, f-lab-kyucumber commented on src/main/java/com/sh/threesentences/auth/config/AuthConfig.java
> +
그냥 PasswordEncoderConfig를 하나 더 만드시면 되지 않을까요? 요런건 너무 고민하지 않으셔도 될 것 같습니다.

2023-02-18 07:50 UTC, f-lab-kyucumber approved these changes

2023-02-18 15:33 UTC, shinsanghooon commented on src/test/java/com/sh/threesentences/users/service/UserServiceTest.java
> +        readingSpaceRepository.deleteAll();
1. 지난번에도 말씀주셨었는데, 아직 SpringBootTest를 제거하지 못했습니다.
2. 그렇네요. 자식 엔티티 쪽에도 soft delete를 적용하는게 맞을 것 같습니다!

2023-02-18 16:50 UTC, merged