Feature/topic
f-lab-edu/three-sentences pull request #31
Opened 2023-02-26 18:01 UTC by shinsanghooon

### 토픽
- #18 
- #19 
- #20 

### 서브 토픽 (테스트 코드 작성 중)
- #21 
- #22 
- #23 

### 문장 (테스트 코드 작성 중)
- #25 
- #26 
- #27

2023-02-28 14:03 UTC, f-lab-kyucumber requested changes

2023-02-28 14:03 UTC, f-lab-kyucumber commented on src/main/java/com/sh/threesentences/common/entity/BaseTimeEntity.java
> +    private Boolean isDeleted = false;
요건 바꾸신 이유를 한번 들어보고 싶네요~ 멘토링 시간에 한번 이야기해보시죠.

2023-02-28 14:03 UTC, f-lab-kyucumber commented on src/main/java/com/sh/threesentences/topic/controller/SentenceController.java
> +    public SentenceResponseDto save(@PathVariable("subtopic-id") Long subTopicId,
이렇게 되면 readingSpaceId는 consume되지 않은 상태라 warning 메시지를 나타내게 될 것 같아요. 혹시 요 부분에 대해서는 어떻게 생각하시나요? 물론 readingSpace 자원 하위에 포함된 것이라 이렇게 디자인되어도 전혀 문제될 부분은 없습니다.

이게 이상하거나 문제가 된다는 것이 아니라, 이런 구조를 만들기 위해 어떤 고민을 하셨을지 궁금해서 질문드려보았습니다. REST API에서 자원을 표시하는 방법에 대해서 여러 의견이 있으니 아래 글도 한번 읽어보시면 좋을 것 같아요.

https://stackoverflow.com/questions/20951419/what-are-best-practices-for-rest-nested-resources

2023-02-28 14:03 UTC, f-lab-kyucumber commented on src/main/java/com/sh/threesentences/topic/controller/PublicTopicController.java
> +        return topicService.getPublicTopics();
ReadingSpace 하위에 토픽이 생기는 구조로 보여요. ReadingSpace 하위의 토픽은 계속 많아질 수 있을 것 같은데 이참에 페이징 관련 API를 활용해 페이징을 제공하는 형태로 개발해보시면 어떨까요?

2023-02-28 14:03 UTC, f-lab-kyucumber commented on src/main/java/com/sh/threesentences/topic/entity/Topic.java
> +    private String naverBookId;
제가 도서 조회 API 스펙을 보진 않았는데요. isbn으로 검색이 되지 않나요?
다른 API를 활용하는 형태로 바뀌진 않겠지만 naverBookId는 네이버라는 시스템에 너무 강결합된 느낌이기도 하고 API 문서 스펙 상 isbn으로의 검색을 제공하지 않을까 싶어서 질문드려봤어요.

2023-02-28 14:03 UTC, f-lab-kyucumber commented on src/main/java/com/sh/threesentences/topic/service/SubTopicService.java
> +        topic.checkDelete();
soft-delete라곤 하지만 매번 삭제되었는지 여부를 체크하는건 굉장히 번거롭고 중복되는 작업일 것 같아요.
아래 힌트를 참고해 deleted된 경우 조회가 되지 않도록 한번 변경해보시겠어요?
```java
@Where(clause = "is_deleted=0")
class Topic
```
Boolean 타입이고 columnDefinition을 따로 bit로 지정하시지 않은 상태라 =0이 아니라 다른걸 넣어야 하실수도 있습니다. 한번 확인하고 적용해보세요.

2023-02-28 14:03 UTC, f-lab-kyucumber commented on src/main/java/com/sh/threesentences/topic/service/TopicService.java
> +        authorityService.checkRoleIsAdmin(readingSpaceMemberRole);
getReadingSpaceMemberRole을 외부에 노출하지 않고 checkRoleIsAdmin 하나만 호출하게 내부 구현 방식을 조금 바꿔보셔도 좋을 것 같아요.

2023-02-28 14:03 UTC, f-lab-kyucumber commented on src/main/java/com/sh/threesentences/users/service/AuthorityService.java
> +    }
중요한 부분은 아니지만 줄바꿈이 굉장히 난해하게 들어가있네요.

```suggestion
        return userReadingSpaceRepository.findByUserAndReadingSpaceId(user, readingSpaceId)
            .orElseThrow(() -> new IllegalStateException(READING_SPACE_NOT_FOUND.getMessage()));
```

가독성도 좋지 않고 불필요하게 라인 수도 늘어나는것 같아요. editorconfig 때문인가요? 혹시 그렇다면 기본 설정을 좀 수정해보시면 좋겠습니다.

2023-02-28 14:03 UTC, f-lab-kyucumber commented on src/main/java/com/sh/threesentences/users/service/AuthorityService.java
> +        }
어드민이 아닌데 수정을 시도한 경우에 IllegalStateException을 던지고 BAD_REQUEST를 응답하는게 좋을까요?

403 Forbidden을 응답하는게 좋지 않을까 생각됩니다. 적절한 표준 예외를 사용해보시고 적절한 예외가 없다면 ForbiddenException 같은 커스텀 예외를 만드시고 ControllerAdvice에 추가하셔도 좋을 것 같네요.

2023-03-01 08:26 UTC, shinsanghooon commented on src/main/java/com/sh/threesentences/common/entity/BaseTimeEntity.java
> +    private Boolean isDeleted = false;
넵 알겠습니다!

2023-03-03 14:06 UTC, shinsanghooon commented on src/main/java/com/sh/threesentences/topic/service/TopicService.java
> +        authorityService.checkRoleIsAdmin(readingSpaceMemberRole);
기존에는 readingSpaceMemberRole을 이용하여 다음 코드인 topicRepository.save에 ReadingSpace 객체를 사용하기 위해 getReadingSpaceMemberRole를 외부에 노출하게 코드를 작성했었습니다. 

보다보니 코드가 조금 지저분해 보이는 느낌(?)도 있어서, authorityService에서는 권한 체크만 진행을 하고, topic을 등록하기 위해 필요한 ReadingSpace는 따로 조회를 하도록 변경하였습니다.

2023-03-11 09:34 UTC, f-lab-kyucumber approved these changes

2023-03-11 09:34 UTC, f-lab-kyucumber commented on src/main/java/com/sh/threesentences/book/controller/BookController.java
> +    }
현재 내부 책 API 구현체는 아래 두가지였던 것 같습니다.
- Kakao
- Naver

그렇다면 KakaoBookProvider를 컨트롤러가 의존하는게 아니라 BookProvider 인터페이스를 의존하는 형태가 더 좋지 않을까요? 이후에 카카오쪽 문제가 생겨 급히 배포를 해야하는 경우가 생긴다면 인터페이스를 그대로 타입으로 사용하고 구체 타입(의존하는 빈)등만 변경해 빠르게 배포할 수 있을 것 같아요.

2023-03-12 07:12 UTC, merged