Feature/monitoring
f-lab-edu/three-sentences pull request #33
Opened 2023-03-18 16:20 UTC by shinsanghooon

**주요 작업 내용**
- 마이크로미터 
- 프로메테우스 
- 그라파나 
- 스프링부트 도커라이징 
- 기본 로깅 작업

2023-03-20 13:03 UTC, f-lab-kyucumber requested changes

2023-03-20 13:03 UTC, f-lab-kyucumber commented on Dockerfile
> +ENTRYPOINT ["java","-jar","app.jar"]
힙 옵션 등의 설정이 빠져있는 것 같습니다.

별도로 스크립트 파일을 분리하고 힙 옵션 등을 해당 파일에서 관리하거나 하는 걸 고려해보셔도 좋을 것 같네요.

2023-03-20 13:03 UTC, f-lab-kyucumber commented on src/main/java/com/sh/threesentences/auth/config/AuthConfig.java
> +            .antMatchers(HttpMethod.GET, "/actuator/**").permitAll()
이렇게 다 열게되면 actuator를 이용해 공격자가 여러 정보를 얻거나 조작을 할 수 있지 않을까요?

필요한 경로(actuator/prometheus, actuator/health)들만 허용하면 어떨까요?

2023-03-20 13:03 UTC, f-lab-kyucumber commented on src/main/java/com/sh/threesentences/common/log/LogTraceAspect.java
> +        String clientUrl = request.getRequestURL().toString();
이런 클라이언트의 ip나 호출 url 등은 nginx access log을 이용해서 식별할 수 있습니다.
이렇게 로그를 매번 남기게 되면 굉장히 많은 로그가 남게 될 것 같은데요. AOP를 이용해 컨트롤러와 서비스의 로그를 다 남기시려고 생각하신 이유를 말씀해주실 수 있나요?

2023-03-20 13:03 UTC, f-lab-kyucumber commented on src/main/resources/application.yml
> +    authorization-header-prefix: KakaoAK
이런 외부 API 토큰 값은 환경 변수 등을 활용해 숨겨주시는게 좋을 것 같네요.

2023-03-20 13:03 UTC, f-lab-kyucumber commented on src/main/resources/application.yml
> +        include: "*"
*로 표시하시게 되면 생각보다 많은 정보를 노출하게 됩니다.

모든 정보가 다 노출되어야 할 필요가 있는지 고민해보시면 좋을 것 같아요. 아래 내용도 한번 읽어보세요.

https://techblog.woowahan.com/9232/

2023-03-20 13:17 UTC, kyucumber commented
그리고 메트릭을 수집해서 그라파나로 보신것까지 스크린샷 등으로 남겨주시면 좀 더 좋을 것 같아요.

2023-03-21 16:41 UTC, shinsanghooon commented on src/main/java/com/sh/threesentences/auth/config/AuthConfig.java
> +            .antMatchers(HttpMethod.GET, "/actuator/**").permitAll()
아래 코멘트에서 공유해주신 링크 잘 보았습니다. 원래는 actuator 포트번호만 다르게 해서 외부 접근을 막으면 되지 않나.. 라고 생각했었는데 조금 안일했던 것 같네요.

관련하여 변경한 내용은 아래와 같습니다.
- health와 prometheus만 enable, exposure 되도록 세팅 해놨습니다. 
- 기본 값인 actuator는 유추해서 접근이 가능하므로 엔드포인트를 쓰지 않고 전혀 관련없는 cheese 라는 엔드포인트로 변경했습니다.
- cheese 엔드포인트로 요청에 대해서 전체 시스템의 ADMIN 권한만 허용되게 변경했습니다.

2023-03-21 16:45 UTC, shinsanghooon commented on src/main/java/com/sh/threesentences/common/log/LogTraceAspect.java
> +        String clientUrl = request.getRequestURL().toString();
모든 호출마다 로그를 남기는 것은 아무래도 서버에 무리가 간다고 말씀해주신 내용은 기억하고 있습니다.  🙂
사실 AOP를 이용해서 로그를 한 번 남겨보고 싶은 개인적은 욕심으로 해보았습니다. 이 부분은 로그가 꼭 필요하다고 생각되는 부분만 남길 수 있도록 수정하겠습니다.

2023-03-22 09:55 UTC, kyucumber commented on src/main/java/com/sh/threesentences/common/log/LogTraceAspect.java
> +        String clientUrl = request.getRequestURL().toString();
이번 멘토링 시간에 nginx랑 관련되어서 이야기를 한번 나눠보죠. 요런 역할을 대체해줄 수 있을 것 같습니다.

2023-03-22 09:55 UTC, kyucumber approved these changes

2023-05-08 14:00 UTC, merged