Settings/multi module
f-lab-edu/three-sentences pull request #4
Opened 2023-01-19 16:15 UTC by shinsanghooon

기본적인 멀티모듈 및 체크스타일 세팅 진행하였습니다.
- 프로젝트가 크지 않고 기능이 많지 않아 멀티모듈은 우선 api, core 정도로 나눠보긴 했습니다. 하지만 모듈을 나누기엔 조금 과하지 않나 하는 생각도 들긴 하네요. 고민이 조금 더 필요할 것 같습니다. 
- 체크스타일은 우선 구글 체크스타일을 사용했으며 사용하면서 설정을 조금씩 바꿔볼 예정입니다.

2023-01-21 12:29 UTC, kyucumber commented
> 프로젝트가 크지 않고 기능이 많지 않아 멀티모듈은 우선 api, core 정도로 나눠보긴 했습니다. 하지만 모듈을 나누기엔 조금 과하지 않나 하는 생각도 들긴 하네요. 고민이 조금 더 필요할 것 같습니다.

이 내용은 슬랙에 남겨두었으니 확인 부탁드립니다.

2023-01-21 13:01 UTC, kyucumber requested changes

2023-01-21 13:01 UTC, kyucumber commented on build.gradle
> +buildscript {
plugins -> buildscript 방식으로 변경하신 이유가 있을까요?
아래 내용을 참고해보시고 특별한 이유가 있는게 아니라면 plugins를 사용해주시면 좋겠습니다.

https://stackoverflow.com/questions/32352816/what-the-difference-in-applying-gradle-plugin

2023-01-21 13:01 UTC, kyucumber commented on build.gradle
> +//    sourceCompatibility = '11'
요건 IntelliJ의 Gradle이나 Intellij runtime이 자바 8로 설정된게 아닐까 싶은데요. 자세한 부분은 멘토링때 한번 같이 볼까요?

이 참에 sourceCompatibility와 targetCompatibility 두개의 차이를 아시는지 멘토링때 한번 다루어봐도 좋겠네요.

2023-01-21 13:01 UTC, kyucumber commented on build.gradle
> +    version '1.0-SNAPSHOT'
버전은 어떤 식으로 관리하실건가요? 요것도 한번 같이 이야기해봐도 좋을 듯 하네요~

[Semantic Versioning 관련 문서](https://spoqa.github.io/2012/12/18/semantic-versioning.html)

2023-01-21 13:01 UTC, kyucumber commented on build.gradle
> +project(':threesentences-api') {
이 설정은 threesentences-api/build.gradle에 넣어도 되지 않을까요~?

2023-01-21 13:01 UTC, kyucumber commented on threesentences-api/src/main/resources/application.yml
> +    url: jdbc:h2:tcp://localhost/~/Documents//Programming/Threesentences
요거 제가 2차 프로젝트 명세에 h2를 쓰라고 잘못 적어둔 것 같습니다. 😭 번거로우시겠지만 로컬에 컨테이너 기반으로 MySQL을 사용하도록 변경하시는건 어떨까요? 

h2를 사용해도 크게 상관은 없으나 오히려 더 불편하시지 않을까 생각되어요. IntelliJ에서 DB를 바로 연결해서 테스트하실 수 있어 조금 더 편하시기도 할테고 컨테이너를 사용해보는 경험도 미리 할 수 있을 것 같아서요.

번거로우시다면 h2를 그대로 사용하셔도 무방하긴 합니다.

2023-01-22 16:28 UTC, shinsanghooon commented on build.gradle
> +//    sourceCompatibility = '11'
넵 인텔리제이에서 11로 변경했는데도 안되더라구요. 한 번 같이 보면 좋을 것 같습니다.

2023-01-22 16:30 UTC, shinsanghooon commented on build.gradle
> +buildscript {
멀티모듈 세팅하면서 참고자료의 세팅을 복붙했습니다 ㅠㅠ 그리고 gradle에 대해서도 공부를 해야할 것 같습니다.

2023-01-22 16:56 UTC, closed without merging

2023-01-22 16:56 UTC, shinsanghooon commented
싱글모듈로 프로젝트를 진행 후, 여유가 된다면 멀티모듈로 변경 해볼 예정