회원 등록 기능 구현
f-lab-edu/three-sentences pull request #9
Opened 2023-01-26 16:21 UTC by shinsanghooon

- 사용자 정보(이메일, 이름, 패스워드)을 입력받아 회원 가입 기능을 구현하기
- 사용자의 멤버십 등급은 Basic을 기본값으로 세팅하기
- Auditing 사용해서 createdAt, updatedAt, createdBy, updatedBy 적용하기
- 이메일 기준으로 계정 중복 확인하기
- Bean Validation을 활용하여 이메일 형식 체크하기
- 단위 테스트 작성하기(일부만 작성하였습니다.)

관련 이슈: #7

2023-01-28 09:47 UTC, kyucumber requested changes

2023-01-28 09:47 UTC, kyucumber commented on src/main/java/com/sh/threesentences/users/exception/UserExceptionHandler.java
> +    }
코드가 많지 않은 상황인데 2개의 커스텀 예외가 만들어졌네요. 커스텀 예외를 활용해도 무방하지만 가급적 모든 예외 상황을 커스텀 예외로 만드시기 보다는 IllegalArgumentException, IllegalStateException 등의 표준 예외를 활용하셔도 좋을 것 같아요.

관련해서 이펙티브 자바에 내용이 있었는데 자세한 내용은 아래 내용 참고 부탁드립니다.

https://jjingho.tistory.com/121

2023-01-28 09:47 UTC, kyucumber commented on src/main/java/com/sh/threesentences/users/entity/Users.java
> +public class Users extends BaseEntity {
Users는 일반적으로 컬렉션 타입, 배열 등이라고 생각하기 쉬워 보이네요.

Users가 아닌 User로 명명하시는게 어떨까요?

2023-01-28 09:47 UTC, kyucumber commented on src/main/java/com/sh/threesentences/users/entity/Users.java
> +    }
엔티티에서 Dto와 결합하고 있네요. 컨트롤러 레이어의 응답 변경이 엔티티까지 전파될 수 있을 것 같은데 좋은 설계일지 고민이 필요해보입니다.

Dto에서 정적 팩토리 메소드를 만들거나 하는 방향이 조금 더 낫지 않을까 생각되어요.

2023-01-28 09:47 UTC, kyucumber commented on src/main/java/com/sh/threesentences/users/repository/UserRepository.java
> +    public Optional<String> findByEmail(@Param("email") String email);
이메일 중복 여부를 체크하려는 목적이라면 `existsBy~`와 같은 형태로 사용하시는게 좀 더 적절할 것 같아요~

2023-01-28 09:47 UTC, kyucumber commented on src/main/java/com/sh/threesentences/utils/PasswordEncoder.java
> +        }
NoSuchAlgorithmException와 같은 구체적인 예외를 다시 catch로 받아서 RunTimeException과 같이 포괄적인 예외로 만들어 다시 던져주고 있네요. 혹시 어떤 의도인지 여쭤봐도 될까요?

2023-01-28 09:47 UTC, kyucumber commented on build.gradle
> +    runtimeOnly 'mysql:mysql-connector-java'
둘중 하나만 사용해도 될 것 같은데 mysql-connector를 추가하신 이유가 있을까요~?

2023-01-28 09:47 UTC, kyucumber commented on src/main/java/com/sh/threesentences/users/controller/UserController.java
> +@Validated
`@Valid`는 JSR-303, `@Validated`는 스프링의 기능으로 기억하고 있는데요. 현재 스프링을 사용하곤 있지만 좀 더 범용적인 JSR-303 기반 Valid를 사용하는게 좀 더 좋지 않을까 하는 생각도 들어요.

그리고 `@Validated`는 AOP 기반으로 동작했던걸로 기억하는데 컨트롤러의 경우 ArgumentResolver 기반으로 동작하는 `@Valid`만 사용해도 충분하지 않을까 생각이 듭니다. 그리고 ControllerAdvice에서도 MethodArgumentNotValidException에 대한 예외를 처리해주고 계신데 `@Validated`의 경우 다른 예외가 던져졌던것 같아서 확인이 필요할 것 같네요.

2023-01-28 09:47 UTC, kyucumber commented on src/main/java/com/sh/threesentences/users/controller/UserController.java
> +@Validated
만약에 테스트 하실 때 MethodArgumentNotValidException가 발생했었다면 `@Valid`로 인해 ArgumentResolver 기반으로 유효성 검증이 동작한게 아닐까 싶은데 요건 한번 확인해보시겠어요?

2023-01-28 09:47 UTC, kyucumber commented on src/test/java/com/sh/threesentences/users/service/UserServiceTest.java
> +@SpringBootTest
단위 테스트가 아닌 통합 테스트를 선택해주신 이유가 있을까요~?

2023-01-28 11:52 UTC, shinsanghooon commented on src/main/java/com/sh/threesentences/users/entity/Users.java
> +    }
⭐️

2023-01-28 11:54 UTC, shinsanghooon commented on src/main/java/com/sh/threesentences/utils/PasswordEncoder.java
> +        }
⭐️

2023-01-28 13:08 UTC, shinsanghooon commented on build.gradle
> +    runtimeOnly 'mysql:mysql-connector-java'
아, 제가 application.yml에 driver-class-name을 mysql 드라이버로 설정해두어서 추가했던 것 같습니다. mariadb 드라이버 사용하도록 수정하겠습니다!

2023-01-28 13:09 UTC, shinsanghooon commented on src/main/java/com/sh/threesentences/users/repository/UserRepository.java
> +    public Optional<String> findByEmail(@Param("email") String email);
마침 스프링 데이터 JPA에서 existBy~ 관련된 메소드도 제공을 해주네요! 변경하도록 하겠습니다.

2023-01-28 13:09 UTC, shinsanghooon commented on src/main/java/com/sh/threesentences/users/entity/Users.java
> +public class Users extends BaseEntity {
앗 알겠습니다.

2023-01-28 13:20 UTC, shinsanghooon commented on src/main/java/com/sh/threesentences/users/exception/UserExceptionHandler.java
> +    }
이펙티브 자바 관련 챕터도 한 번 읽어보겠습니다.

2023-01-28 15:07 UTC, shinsanghooon commented on src/main/java/com/sh/threesentences/users/controller/UserController.java
> +@Validated
간단하게 두 어노테이션의 차이점에 대해서 작성해보았습니다. 

`@Valid`
- ArgumentResolver를 기반으로 동작하기 때문에 컨트롤러 메소드의 유효성 검증만 가능
- 유효성 검증에 실패하면 MethodArgumentNotValidException 예외가 던져짐

`@Validated`
- AOP 기반으로 MethodValidationInterceptor가 등록되고 메소드 요청을 가로채 유효성 검증을 진행
- 유효성 검증에 실패하면 ConstraintViolationException 예외가 던져짐
- 컨트롤러에 해당 어노테이션을 추가하여 RequestParam와 PathVariable을 검증

2023-01-28 15:10 UTC, shinsanghooon commented on src/main/java/com/sh/threesentences/users/controller/UserController.java
> +    }
`@RequestParam` 에 대한 유효성 검증을 위해 `@Validated`가 필요한 것으로 확인했습니다.

2023-01-29 13:52 UTC, shinsanghooon commented on src/test/java/com/sh/threesentences/users/service/UserServiceTest.java
> +@SpringBootTest
JPA 관련 기능이 정상적으로 동작하는지 테스트를 해보고 싶어서 사용했습니다. 혹시 다른 추천해주실만한 방법이 있을까요?

2023-01-29 14:35 UTC, shinsanghooon commented on src/main/java/com/sh/threesentences/utils/PasswordEncoder.java
> +        }
그리고 RuntimeException은 여러 예외를 포괄하는 특징을 가지고 있어서 RuntimeNoSuchAlgorithmException으로 전환하도록 변경하였습니다.

2023-01-30 09:34 UTC, kyucumber commented on src/main/java/com/sh/threesentences/utils/PasswordEncoder.java
> +        }
NoSuchAlogrithmException 아 요게 CheckedException이었군요. 

RuntimeNoSuchAlgorithmException를 만들어주셨는데 IllegalStateExcetion을 활용해도 괜찮을 것 같네요.

2023-01-30 09:36 UTC, kyucumber commented on src/test/java/com/sh/threesentences/users/service/UserServiceTest.java
> +@SpringBootTest
지금 서비스에 로직이 별로 없긴 한데 서비스는 서비스에서 작성하신 기능이 제대로 동작하는지를 중점적으로 테스트하는게 좋다고 생각해요. 그런 관점이라면 단위 테스트가 조금 더 적절할 수 있다고 생각합니다.

말씀하신 JPA와 관련된 기능이 정상적으로 동작하는지 테스트하시려는거라면 Repository를 통합 테스트로 만드셔도 될 것 같네요. 사실 hibernate에서 제공하는거라 별도로 테스트할 필욘 없다고 생각하지만 확인을 목적으로 하시는거면 만드셔도 무방할 것 같습니다.

2023-01-30 09:37 UTC, kyucumber commented on src/test/java/com/sh/threesentences/users/service/UserServiceTest.java
> +@SpringBootTest
모든 부분을 통합 테스트로 작성하시거나 하는 분도 계시거든요. 그래서 여쭤본거였어요. JPA쪽이 잘 동작하는지를 보시려는 의도라면 통합 테스트로 작성하셔도 무방하니 원하시는 방향으로 하시면 됩니다~

2023-01-30 09:37 UTC, kyucumber commented on src/main/java/com/sh/threesentences/users/controller/UserController.java
> +    }
필요하다면 Param이 하나밖에 없긴 하지만 Dto로 묶고 @Valid를 활용하는 방법도 선택할 수 있긴 하겠네요~

2023-01-30 09:38 UTC, kyucumber approved these changes

2023-01-30 12:44 UTC, merged